"use client";

/**
 * Enrollment + unlock flow.
 *
 * 1. Student enters their roll number (identity claimed out-of-band —
 *    a production deployment would verify this against student records).
 * 2. A non-extractable ECDSA P-256 punch key is generated by the browser.
 *    On supporting platforms this key lives in the TEE / StrongBox /
 *    Secure Enclave and can never be exported — the hardware root of trust.
 * 3. A passkey (WebAuthn, userVerification: required) is registered and
 *    gates every future punch-signing session.
 */

import { generatePunchKey } from "@/lib/protocol";

import { useState } from "react";
import {
  beginEnrollment,
  completePasskeyRegistration,
  finishEnrollment,
  passkeyRegistrationOptions,
  loginUser,
  registerUser,
} from "@/lib/api";

export interface EnrollResult {
  keyPair: CryptoKeyPair;
  kid: string;
  sid: string;
}

function b64urlEncode(data: Uint8Array | string): string {
  const bytes = typeof data === "string" ? new TextEncoder().encode(data) : data;
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function b64urlDecodeToBinary(segment: string): string {
  const b64 = segment.replace(/-/g, "+").replace(/_/g, "/");
  return atob(b64 + "=".repeat((4 - (b64.length % 4)) % 4));
}

function b64urlBytes(segment: string): Uint8Array {
  return Uint8Array.from(b64urlDecodeToBinary(segment), (c) => c.charCodeAt(0));
}

// Helper to convert Uint8Array to ArrayBuffer for strict TS5.7+ WebAuthn types
function toArrayBuffer(bytes: Uint8Array): ArrayBuffer {
  const buf = new ArrayBuffer(bytes.byteLength);
  new Uint8Array(buf).set(bytes);
  return buf;
}

/** Derive the same key ID the server stores — proves parity at enroll time. */
export async function kidFromKeyPairExported(keyPair: CryptoKeyPair): Promise<string> {
  return kidFromKeyPair(keyPair);
}

async function kidFromKeyPair(keyPair: CryptoKeyPair): Promise<string> {
  const jwk = (await crypto.subtle.exportKey("jwk", keyPair.publicKey)) as JsonWebKey & {
    x: string;
    y: string;
  };
  const dec = (b: string) => {
    const bin = atob(b.replace(/-/g, "+").replace(/_/g, "/") + "=".repeat((4 - (b.length % 4)) % 4));
    return Uint8Array.from(bin, (c) => c.charCodeAt(0));
  };
  const x = dec(jwk.x);
  const y = dec(jwk.y);
  const digest = await crypto.subtle.digest("SHA-256", buildKidInput(x, y) as unknown as ArrayBuffer);
  return b64urlEncode(new Uint8Array(digest));
}

function buildKidInput(x: Uint8Array, y: Uint8Array): Uint8Array {
  const prefix = new TextEncoder().encode("punch-p256:");
  const colon = new TextEncoder().encode(":");
  const out = new Uint8Array(prefix.length + x.length + colon.length + y.length);
  let off = 0;
  out.set(prefix, off); off += prefix.length;
  out.set(x, off); off += x.length;
  out.set(colon, off); off += colon.length;
  out.set(y, off);
  return out;
}

import OrgSelector, { type OrgSlug } from "./OrgSelector";

export default function EnrollFlow({
  onEnrolled,
}: {
  onEnrolled: (result: EnrollResult) => void;
}) {
  const [isLogin, setIsLogin] = useState(true);
  const [orgSlug, setOrgSlug] = useState<OrgSlug>("campus");
  const [loading, setLoading] = useState(false);
  const [authError, setAuthError] = useState<string | null>(null);

  return (
    <main className="punch-shell">
      <header className="punch-header">
        <div>
          <p className="punch-kicker">Punch Attendance</p>
          <h1 className="punch-title">{isLogin ? "Student Login" : "Register Student"}</h1>
        </div>
      </header>

      <form
        className="enroll-form"
        onSubmit={async (event) => {
          event.preventDefault();
          setAuthError(null);
          setLoading(true);
          const form = new FormData(event.currentTarget);
          const roll = String(form.get("roll") ?? "").trim();
          const password = String(form.get("password") ?? "").trim();
          const email = String(form.get("email") ?? "").trim();
          const name = String(form.get("name") ?? "").trim();
          const label = String(form.get("label") ?? "This phone").trim() || "This phone";

          try {
            // 1. Student Authentication
            let authRoll = roll;
            if (isLogin) {
              const res = await loginUser({ studentId: roll, password });
              if (res.token) {
                localStorage.setItem("punch.token.v1", res.token);
              }
              authRoll = res.user.studentId || roll;
            } else {
              const res = await registerUser({
                email,
                password,
                name: name || roll,
                role: "student",
                studentId: roll,
              });
              if (res.token) {
                localStorage.setItem("punch.token.v1", res.token);
              }
              authRoll = res.user.studentId || roll;
            }

            // 2. Identity -> server challenge
            const enroll = await beginEnrollment(authRoll);
            // 3. Hardware-bound key
            const generated = await generatePunchKey();
            const keyPair = generated.keyPair;
            const kid = await kidFromKeyPair(keyPair);

            // 4. Server stores the public half & revokes older keys
            await finishEnrollment({
              studentId: authRoll,
              publicKeyJwk: await exportJwk(keyPair),
              challenge: enroll.challenge,
              label,
            });

            // 5. Passkey gate (biometric / PIN)
            const WEBAUTHN_TIMEOUT_MS = 30000;
            try {
              const options = await passkeyRegistrationOptions(authRoll);
              const createPromise = navigator.credentials.create({
                publicKey: {
                  rp: options.publicKey.rp as PublicKeyCredentialRpEntity,
                  user: {
                    id: toArrayBuffer(b64urlBytes(options.publicKey.user.id)),
                    name: options.publicKey.user.name,
                    displayName: options.publicKey.user.displayName,
                  },
                  challenge: toArrayBuffer(b64urlBytes(options.publicKey.challenge)),
                  pubKeyCredParams: options.publicKey.pubKeyCredParams as PublicKeyCredentialParameters[],
                  timeout: options.publicKey.timeout,
                  attestation: options.publicKey.attestation as AttestationConveyancePreference,
                  authenticatorSelection: options.publicKey.authenticatorSelection as AuthenticatorSelectionCriteria,
                },
              });
              const timeoutPromise = new Promise<null>((resolve) =>
                setTimeout(() => resolve(null), WEBAUTHN_TIMEOUT_MS),
              );
              const credential = await Promise.race([createPromise, timeoutPromise]);
              if (credential) {
                await completePasskeyRegistration(authRoll, credential);
              } else {
                console.warn("Passkey registration timed out — skipped");
              }
            } catch (passkeyErr) {
              console.warn("Passkey registration skipped:", passkeyErr);
            }

            onEnrolled({ keyPair, kid, sid: `punch:${orgSlug}:${authRoll}` });
          } catch (error) {
            setAuthError((error as Error).message || "Authentication & Enrollment failed");
          } finally {
            setLoading(false);
          }
        }}
      >
        <OrgSelector value={orgSlug} onChange={setOrgSlug} />

        <label className="field">
          <span>Roll number / ID</span>
          <input name="roll" required placeholder="e.g. 22B81A0595" autoComplete="off" />
        </label>

        {!isLogin ? (
          <>
            <label className="field">
              <span>Full Name</span>
              <input name="name" required placeholder="John Doe" autoComplete="name" />
            </label>
            <label className="field">
              <span>Email</span>
              <input name="email" type="email" required placeholder="student@college.edu" autoComplete="email" />
            </label>
          </>
        ) : null}

        <label className="field">
          <span>Password</span>
          <input name="password" type="password" required placeholder="••••••••" autoComplete="current-password" />
        </label>

        <label className="field">
          <span>Device label</span>
          <input name="label" defaultValue="This phone" />
        </label>

        {authError ? <p className="error-text">{authError}</p> : null}

        <button className="btn-primary" type="submit" disabled={loading}>
          {loading ? "Authenticating & Binding Device…" : isLogin ? "Login & Bind Hardware Key" : "Register & Bind Hardware Key"}
        </button>

        <button
          type="button"
          className="btn-ghost"
          onClick={() => {
            setIsLogin(!isLogin);
            setAuthError(null);
          }}
        >
          {isLogin ? "Need a new account? Register" : "Already registered? Sign In"}
        </button>
      </form>
      <p className="hint">
        Your institutional login authenticates your identity. A fresh non-extractable key is generated inside this device&apos;s secure hardware to prevent proxy attendance.
      </p>
    </main>
  );
}

async function exportJwk(keyPair: CryptoKeyPair): Promise<unknown> {
  const jwk = (await crypto.subtle.exportKey("jwk", keyPair.publicKey)) as JsonWebKey & {
    x: string;
    y: string;
  };
  return { kty: "EC", crv: "P-256", x: jwk.x, y: jwk.y };
}

export async function unlockWithPasskey(
  studentId: string,
  assertionOptions: {
    publicKey: {
      challenge: string;
      rpId: string;
      timeout: number;
      userVerification: string;
      allowCredentials: Array<{ type: string; id: string }>;
    };
  }
): Promise<unknown> {
  const assertion = await navigator.credentials.get({
    publicKey: {
      challenge: toArrayBuffer(b64urlBytes(assertionOptions.publicKey.challenge)),
      rpId: assertionOptions.publicKey.rpId,
      timeout: assertionOptions.publicKey.timeout,
      userVerification: assertionOptions.publicKey.userVerification as UserVerificationRequirement,
      allowCredentials: assertionOptions.publicKey.allowCredentials.map((c) => ({
        type: c.type as "public-key",
        id: toArrayBuffer(b64urlBytes(c.id)),
      })),
    },
  });
  return assertion;
}
