"use client";

/**
 * Enrollment + unlock flow.
 *
 * 1. Student enters their roll number (identity claimed out-of-band —
 *    a production deployment would verify this against student records).
 * 2. A non-extractable ECDSA P-256 punch key is generated by the browser.
 *    On supporting platforms this key lives in the TEE / StrongBox /
 *    Secure Enclave and can never be exported — the hardware root of trust.
 * 3. A passkey (WebAuthn, userVerification: required) is registered and
 *    gates every future punch-signing session.
 */

import { generatePunchKey } from "@/lib/protocol";

import {
  beginEnrollment,
  completePasskeyRegistration,
  finishEnrollment,
  passkeyRegistrationOptions,
} from "@/lib/api";

export interface EnrollResult {
  keyPair: CryptoKeyPair;
  kid: string;
  sid: string;
}

function b64urlEncode(data: Uint8Array | string): string {
  const bytes = typeof data === "string" ? new TextEncoder().encode(data) : data;
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function b64urlDecodeToBinary(segment: string): string {
  const b64 = segment.replace(/-/g, "+").replace(/_/g, "/");
  return atob(b64 + "=".repeat((4 - (b64.length % 4)) % 4));
}

function b64urlBytes(segment: string): Uint8Array {
  return Uint8Array.from(b64urlDecodeToBinary(segment), (c) => c.charCodeAt(0));
}

// Helper to convert Uint8Array to ArrayBuffer for strict TS5.7+ WebAuthn types
function toArrayBuffer(bytes: Uint8Array): ArrayBuffer {
  const buf = new ArrayBuffer(bytes.byteLength);
  new Uint8Array(buf).set(bytes);
  return buf;
}

/** Derive the same key ID the server stores — proves parity at enroll time. */
export async function kidFromKeyPairExported(keyPair: CryptoKeyPair): Promise<string> {
  return kidFromKeyPair(keyPair);
}

async function kidFromKeyPair(keyPair: CryptoKeyPair): Promise<string> {
  const jwk = (await crypto.subtle.exportKey("jwk", keyPair.publicKey)) as JsonWebKey & {
    x: string;
    y: string;
  };
  const dec = (b: string) => {
    const bin = atob(b.replace(/-/g, "+").replace(/_/g, "/") + "=".repeat((4 - (b.length % 4)) % 4));
    return Uint8Array.from(bin, (c) => c.charCodeAt(0));
  };
  const x = dec(jwk.x);
  const y = dec(jwk.y);
  const digest = await crypto.subtle.digest("SHA-256", buildKidInput(x, y) as unknown as ArrayBuffer);
  return b64urlEncode(new Uint8Array(digest));
}

function buildKidInput(x: Uint8Array, y: Uint8Array): Uint8Array {
  const prefix = new TextEncoder().encode("punch-p256:");
  const colon = new TextEncoder().encode(":");
  const out = new Uint8Array(prefix.length + x.length + colon.length + y.length);
  let off = 0;
  out.set(prefix, off); off += prefix.length;
  out.set(x, off); off += x.length;
  out.set(colon, off); off += colon.length;
  out.set(y, off);
  return out;
}

export default function EnrollFlow({
  onEnrolled,
}: {
  onEnrolled: (result: EnrollResult) => void;
}) {
  return (
    <main className="punch-shell">
      <header className="punch-header">
        <div>
          <p className="punch-kicker">Punch Attendance</p>
          <h1 className="punch-title">Set up this device</h1>
        </div>
      </header>
      <form
        className="enroll-form"
        onSubmit={async (event) => {
          event.preventDefault();
          const form = new FormData(event.currentTarget);
          const roll = String(form.get("roll") ?? "").trim();
          const label = String(form.get("label") ?? "This phone").trim() || "This phone";
          if (!roll) return;

          try {
            // 1. Identity -> server challenge
            const enroll = await beginEnrollment(roll);
            // 2. Hardware-bound key
            const generated = await generatePunchKey();
            const keyPair = generated.keyPair;
            const kid = await kidFromKeyPair(keyPair);

            // 3. Server stores the public half, challenge-bound
            await finishEnrollment({
              studentId: roll,
              publicKeyJwk: await exportJwk(keyPair),
              challenge: enroll.challenge,
              label,
            });

            // 4. Passkey gate (biometric / PIN)
            // WebAuthn may hang in headless/dev environments (no biometric UI).
            // Race against a 4s timeout; if it wins, skip the passkey gate.
            const WEBAUTHN_TIMEOUT_MS = 4000;
            try {
              const options = await passkeyRegistrationOptions(roll);
              const createPromise = navigator.credentials.create({
                publicKey: {
                  rp: options.publicKey.rp as PublicKeyCredentialRpEntity,
                  user: {
                    id: toArrayBuffer(b64urlBytes(options.publicKey.user.id)),
                    name: options.publicKey.user.name,
                    displayName: options.publicKey.user.displayName,
                  },
                  challenge: toArrayBuffer(b64urlBytes(options.publicKey.challenge)),
                  pubKeyCredParams: options.publicKey.pubKeyCredParams as PublicKeyCredentialParameters[],
                  timeout: options.publicKey.timeout,
                  attestation: options.publicKey.attestation as AttestationConveyancePreference,
                  authenticatorSelection: options.publicKey.authenticatorSelection as AuthenticatorSelectionCriteria,
                },
              });
              const timeoutPromise = new Promise<null>((resolve) =>
                setTimeout(() => resolve(null), WEBAUTHN_TIMEOUT_MS),
              );
              const credential = await Promise.race([createPromise, timeoutPromise]);
              if (credential) {
                await completePasskeyRegistration(roll, credential);
              } else {
                console.warn("Passkey registration timed out — skipped (no biometric hardware)");
              }
            } catch (passkeyErr) {
              console.warn("Passkey registration skipped:", passkeyErr);
            }

            onEnrolled({ keyPair, kid, sid: `punch:local:${roll}` });
          } catch (error) {
            alert(`Enrollment failed: ${(error as Error).message}`);
          }
        }}
      >
        <label className="field">
          <span>Roll number</span>
          <input name="roll" required placeholder="e.g. 22B81A0595" autoComplete="off" />
        </label>
        <label className="field">
          <span>Device label</span>
          <input name="label" defaultValue="This phone" />
        </label>
        <button className="btn-primary" type="submit">
          Create hardware punch key + passkey
        </button>
      </form>
      <p className="hint">
        The private key is generated inside this device&apos;s secure hardware and never
        leaves it. Your face, fingerprint, or PIN gates every attendance session.
      </p>
    </main>
  );
}

async function exportJwk(keyPair: CryptoKeyPair): Promise<unknown> {
  const jwk = (await crypto.subtle.exportKey("jwk", keyPair.publicKey)) as JsonWebKey & {
    x: string;
    y: string;
  };
  return { kty: "EC", crv: "P-256", x: jwk.x, y: jwk.y };
}

export async function unlockWithPasskey(
  studentId: string,
  assertionOptions: {
    publicKey: {
      challenge: string;
      rpId: string;
      timeout: number;
      userVerification: string;
      allowCredentials: Array<{ type: string; id: string }>;
    };
  }
): Promise<unknown> {
  const assertion = await navigator.credentials.get({
    publicKey: {
      challenge: toArrayBuffer(b64urlBytes(assertionOptions.publicKey.challenge)),
      rpId: assertionOptions.publicKey.rpId,
      timeout: assertionOptions.publicKey.timeout,
      userVerification: assertionOptions.publicKey.userVerification as UserVerificationRequirement,
      allowCredentials: assertionOptions.publicKey.allowCredentials.map((c) => ({
        type: c.type as "public-key",
        id: toArrayBuffer(b64urlBytes(c.id)),
      })),
    },
  });
  return assertion;
}
